/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppSettingsImport } from './routes/app/settings'
import { Route as AppReturnsImport } from './routes/app/returns'
import { Route as AppOrdersImport } from './routes/app/orders'
import { Route as AppItemsImport } from './routes/app/items'
import { Route as AppInventoryImport } from './routes/app/inventory'
import { Route as AppDashboardImport } from './routes/app/dashboard'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppSettingsRoute = AppSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppReturnsRoute = AppReturnsImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppOrdersRoute = AppOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppItemsRoute = AppItemsImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppInventoryRoute = AppInventoryImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppRouteImport
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryImport
      parentRoute: typeof AppRouteImport
    }
    '/app/items': {
      id: '/app/items'
      path: '/items'
      fullPath: '/app/items'
      preLoaderRoute: typeof AppItemsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersImport
      parentRoute: typeof AppRouteImport
    }
    '/app/returns': {
      id: '/app/returns'
      path: '/returns'
      fullPath: '/app/returns'
      preLoaderRoute: typeof AppReturnsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppItemsRoute: typeof AppItemsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppReturnsRoute: typeof AppReturnsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppItemsRoute: AppItemsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppReturnsRoute: AppReturnsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/items': typeof AppItemsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/returns': typeof AppReturnsRoute
  '/app/settings': typeof AppSettingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/items': typeof AppItemsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/returns': typeof AppReturnsRoute
  '/app/settings': typeof AppSettingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/items': typeof AppItemsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/returns': typeof AppReturnsRoute
  '/app/settings': typeof AppSettingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/items'
    | '/app/orders'
    | '/app/returns'
    | '/app/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/items'
    | '/app/orders'
    | '/app/returns'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/items'
    | '/app/orders'
    | '/app/returns'
    | '/app/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/app",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/app": {
      "filePath": "app/route.jsx",
      "children": [
        "/app/dashboard",
        "/app/inventory",
        "/app/items",
        "/app/orders",
        "/app/returns",
        "/app/settings"
      ]
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/app/dashboard": {
      "filePath": "app/dashboard.jsx",
      "parent": "/app"
    },
    "/app/inventory": {
      "filePath": "app/inventory.jsx",
      "parent": "/app"
    },
    "/app/items": {
      "filePath": "app/items.jsx",
      "parent": "/app"
    },
    "/app/orders": {
      "filePath": "app/orders.jsx",
      "parent": "/app"
    },
    "/app/returns": {
      "filePath": "app/returns.jsx",
      "parent": "/app"
    },
    "/app/settings": {
      "filePath": "app/settings.jsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
